linters:
  enable-all: true
linters-settings:
  goimports:
    local-prefixes: github.com/wcademy
  gocritic:
    enabled-tags:
      - style
      - experimental
issues:
  exclude:
    # False positive for table tests
    # https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope `tt` in function literal
